### ISSUE TITLE
"Select This GIF" text is squished on smaller screens

### ISSUE THREAD

**Issue by alexrabin** [maxland255/flutter_giphy#3]
There should be some padding around the "Select This GIF" text and the text should be center aligned.
![Screenshot 2024-12-13 at 4 19 37 PM](https://github.com/user-attachments/assets/b6bea428-f43e-4ef0-a011-942d4336e6c8)

**Comment by maxland255** [comment]
You're right, I'll add a padding to correct this, I'll release the update tomorrow.

**Comment by maxland255** [comment]
Integrated in 1.0.10 of package

**Comment by alexrabin** [comment]
This is an edge case for super small screens but I feel like it should still be handled. It seems like the button has a fixed height, but the height should be dynamic based on the size of the text.

<img width="381" alt="Screenshot 2024-12-17 at 10 07 14 AM" src="https://github.com/user-attachments/assets/053248bf-e8f6-473d-9022-a204702be6f5" />

**Comment by maxland255** [comment]
I fixed this in 1.0.11 package version
