### ISSUE TITLE
Add option to use higher quality images on the grid view

### ISSUE THREAD

**Issue by alexrabin** [maxland255/flutter_giphy#4]
It would be nice if we had the option to show the higher resolution images in the grid view. We can give a disclaimer saying that this feature will have a higher load on the network due to downloading larger images.

![Screenshot 2024-12-16 at 10 36 47 AM](https://github.com/user-attachments/assets/b1534978-0c97-4198-bbf4-ed0173cd5b71)

**Comment by maxland255** [comment]
Ok, maybe I suggest the `downsizedSmall` version (+-200kb) or then `downsizedMedium` (+-5mb) with an option in `GiphyUIConfig`?
`downsizedSmall` is still light enough for gif previews with decent quality
`downsizedMedium` has better quality but will still be much heavier to load
I therefore propose an option as I said that would display the `downsizedSmall` version if available.

**Comment by alexrabin** [comment]
Could we create an enum with every available size option and then allow the user to select whichever one they want?

**Comment by alexrabin** [comment]
For example:

```dart

enum PreviewOptions {
    original, large, medium, small
}

**Comment by maxland255** [comment]
Ohh okay, it's a good idea 👍

**Comment by maxland255** [comment]
Integrated in 1.0.10 of package
